-- UTILIZAR UM COMENTARIO EM UMA LINHA (SINAL DE MENOS DOBRADO)
/*
SELECT
    *
FROM

PARA COMENTAR UM BLOCO, DIVERSAS LINHAS, UTILIZA /* E 
*/
-- ESTRUTURA DO COMANDO DML SELECT
SELECT -- AS COLUNAS A SEREM PROJETADAS, SEPARADAS POR V RGULA
       -- PARA PROJETAR TODAS AS COLUNAS DA ORIGEM (FROM) UILIZAR O *
FROM -- TRAZER A ORIGEM DE ONDE SER O EXTRA DOS OS DADOS
     -- PODER SER TABELAS, VIEWS, SUBQUERIES
WHERE -- PARA RESTRI  O DE LINHAS. MOSTRAR AS LINHAS QUE ATENDAM
      -- UMA CONDI  O (UTILIZAR OS OPERADORES RELACIONAIS: =, >=, <=, <> !=, >, <
      -- OPERADORES LÓGICOS: NOT, AND, OR
      -- OUTROS OPERADORES: BETWEEN, LIKE)
GROUP BY -- ORGANIZAR O RESULTADO COM SUB GRUPOS
HAVING -- PARA RESTRI  O DE SUBGRUPOS (PODE SER UTILIZADOS OS MESMOS OPERADORES
       -- DA CL USULA WHERE
ORDER BY -- UTILIZADA PARA ORDENAR O RESULTADO
; -- ; FINALIZA A QUERY

-- UITLIZAR O SELECT PARA PRODUZIR VALORES CONSTANTES. PEX: UM CALCULO
SELECT TO_NUMBER(TO_CHAR(TRUNC((  23423423  *   242334) /   4324234,1),'0000000,000000')) AS CALCULO,
       ((  23423423  *   242334) /   4324234.6) AS CALCULO1,
       TO_NUMBER(TRUNC((  23423423  *   242334) /   4324234,1)) AS CALCULO2,
       TO_CHAR(SYSDATE - 4,'DD-MM-YYYY'),
       TO_CHAR(SYSDATE,'YYYY') ANO
FROM SYS.DUAL;

SELECT TO_NUMBER(TO_CHAR(TRUNC((  23423423  *   242334) /   4324234,1),'0000000,000000')) AS CALCULO,
       TO_NUMBER(TRUNC((  23423423  *   242334) /   4324234,1)) AS CALCULO2,
       TO_CHAR(SYSDATE - 4,'DD-MM-YYYY'),
       TO_CHAR(SYSDATE,'YYYY') ANO,
       ID
FROM EMP
WHERE MOD(ID,2)=0
ORDER BY ID DESC;

-- UITLIZAR O SELECT PARA PRODUZIR VALORES CONSTANTES COM RESULTADOS DE TABELAS/VIEW
-- EXPLORANDO AS INFORMAÃ‡Ã•ES EXISTENTES NO DD (CATÃ?LOGO) DO ORACLE
SHOW USER; -- PARA MOSTRAR O USUÃ?RIO LOGADO

-- ACESSANDO O DICIONÁRIO DE DADOS - DD (CATÁLOGO)
-- ALL_OBJECTS É UMA VIEW QUE PERMITE VISUALIZAR TODOS OS OBJETOS QUE O USUÁRIO LOGADO PODE ACESSAR
DESC ALL_OBJECTS; -- DESC DESCREVE A ESTRUTURA DA TABELA / VIEW

SELECT *    -- MOSTRA TODOS OS OBJETOS QUE O USUÁRIO LOGADO PODE VISUALIZAR
FROM ALL_OBJECTS;  

SELECT *    -- MOSTRA SOMENTE O OBJETO COM NOME ALL_OBJECTS
FROM ALL_OBJECTS
WHERE OBJECT_NAME='ALL_OBJECTS';  

SELECT DISTINCT OBJECT_TYPE  -- OBJETOS DISTINTOS QUE O USUÁRIO PODE VISUALIZAR
FROM ALL_OBJECTS;

SELECT COUNT(*)  -- CONTANDO TODAS AS LINHAS DA ALL_OBJECTS  
FROM ALL_OBJECTS;

SELECT COUNT(*)  -- CONTANDO TODAS AS LINHAS DA ALL_OBJECTS  
FROM ALL_OBJECTS;

SELECT OBJECT_NAME
FROM ALL_OBJECTS
WHERE OBJECT_TYPE='VIEW'
  AND OBJECT_NAME LIKE '%CONST%';  

-- CRIANDO TABELAS 
DROP TABLE TA CASCADE CONSTRAINT;

CREATE TABLE TA (
C1      NUMBER  CONSTRAINT PK_TA PRIMARY KEY  ,
C2      VARCHAR2(50) NOT NULL,
C3      CHAR
);

-- CONSIDERANDO A PK COMPOSTA COM DUAS COLUNAS COM UMA REGRA QUE C1 SÓ TEM VALORES MAIORES QUE 0
CREATE TABLE TA (
C1      NUMBER    ,
C2      VARCHAR2(50)   NOT NULL,
C3      CHAR,
CONSTRAINT PK_TA PRIMARY KEY (C1,C2),
CONSTRAINT CK_C1_POS CHECK (C1 > 0)
);

-- CRIANDO TABELA TB 
DROP TABLE TB;

CREATE TABLE TB (
COL1      NUMBER(3)   ,
COL2      NUMBER(5,2) NOT NULL,
C1_TA     NUMBER NULL,
CONSTRAINT PK_TB PRIMARY KEY (COL1),
CONSTRAINT FK_TB_TA FOREIGN KEY (C1_TA) REFERENCES TA (C1)
);

-- ALTERANDO TABELAS 
-- RENOMEAR TABELA, RENOMER COLUNA, ADICIONAR COLUNA, ADICIONAR REGRAS,
-- MODIFICAR COLUNAS, ELIMINAR REGRAS E COLUNAS (ADD, DROP, RENAME, MODIFY)
-- RENOMEAR A TABELA
ALTER TABLE TA RENAME TO TC;

-- ADICIONAR COLUNA PARA TABELA
ALTER TABLE TA 
ADD  C4 DATE NOT NULL
ADD  C5 DATE;

-- RENOMEAR COLUNA DA TABELA
ALTER TABLE TA 
RENAME COLUMN C5 TO TESTE;

-- MODIFICAR COLUNA DA TABELA
ALTER TABLE TA 
MODIFY  C4 NULL;

-- ELIMINAR COLUNA DA TABELA
ALTER TABLE TA 
DROP  COLUMN TESTE ;

-- ELIMINAR CONSTRAINT (REGRA) DA TABELA
ALTER TABLE TB 
DROP  CONSTRAINT FK_TB_TA  ;

-- ADICIONAR CONSTRAINT (REGRA) PARA TABELA
ALTER TABLE TB 
ADD  CONSTRAINT FK_TB_TA FOREIGN KEY (C1_TA) REFERENCES TA (C1) ;

-- ADICIONAR CONSTRAINT (REGRA) PARA TABELA
ALTER TABLE TA 
ADD  CONSTRAINT CK_C1_POS CHECK (C1 > 0) ;

-- VISUALIZAR AS INFORMAÇÕES DA TABELA CRIADA (CONFIRMAR A EXISTÊNCIA DA TABELA NO PROJETO)
-- DESCREVENDO SUCINTAMENTE A ESTRUTURA DA TABELA
DESC TA;
DESC TB;

-- ACESSANDO O DD (CATÁLOGO)
SELECT *
FROM USER_TABLES
WHERE --TABLE_NAME='TA';
      TABLE_NAME IN ('TA','TB');

-- ACESSANDO AS COLUNAS DA TABELA CRIADA NO DD (CATÁLOGO)
SELECT *
FROM USER_TAB_COLUMNS
WHERE --TABLE_NAME='TA';
      TABLE_NAME IN ('TA','TB');

-- ACESSANDO AS REGRAS (CONSTRAINTS) DA TABELA CRIADA NO DD (CATÁLOGO)
SELECT *
FROM USER_CONSTRAINTS
WHERE --TABLE_NAME='TA';
      TABLE_NAME IN ('TA','TB');

-- ACESSANDO AS REGRAS (CONSTRAINTS) DA TABELA CRIADA NO DD (CATÁLOGO)
SELECT *
FROM USER_CONS_COLUMNS
WHERE --TABLE_NAME='TA';
      TABLE_NAME IN ('TA','TB');
      
-- BD2 - 2o Bim -Atividade de SQL - Exercícios de DDL - Tabelas do Projeto Pedido - Parte 1
DROP TABLE CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE (
CODIGO          NUMBER     ,
NOME            VARCHAR2(60) NOT NULL,
RUA             VARCHAR2(80) NOT NULL,
NR              NUMBER(4) NOT NULL,
BAIRRO          VARCHAR2(50) NOT NULL,
COMPLEMENTO     VARCHAR2(100) NULL,
CIDADE          VARCHAR2(50) NOT NULL,
UF              VARCHAR2(2) NOT NULL,
CEP             VARCHAR2(10) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO)
);

DESC CLIENTE;

SELECT *
FROM USER_TABLES
WHERE TABLE_NAME IN ('CLIENTE','FONE_CLIENTE');

DROP TABLE FONE_CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE FONE_CLIENTE (
NUMERO          VARCHAR2(14),
CODIGO_CLI      NUMBER,
CONSTRAINT PK_FONE_CLIENTE PRIMARY KEY (NUMERO,CODIGO_CLI),
CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO)
);

-- CASO QUEIRA IMPLEMENTAR A FK EXTERNAMENTE
ALTER TABLE FONE_CLIENTE
CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO);

-- CRIANDO INDICES
DESC TA;

DROP INDEX IND_TA_C2;

CREATE  UNIQUE  INDEX IND_TA_C2 ON TA (C2 );
CREATE    INDEX IND_TA_C2 ON TA (C2 DESC);

SELECT *
FROM USER_INDEXES
WHERE INDEX_NAME='IND_TA_C2';

SELECT *
FROM USER_IND_COLUMNS
WHERE INDEX_NAME='IND_TA_C2';

-- CRIANDO SEQUENCES
DROP SEQUENCE SEQ_TA;

CREATE SEQUENCE SEQ_TA;
-- PARÂMETROS PARA A CRIAR SEQUENCE
-- MINVALUE, MAXVALUE, INCREMENT BY, CYCLE, ORDER, START WITH CACHE
CREATE SEQUENCE SEQ_TA INCREMENT BY 5 CACHE 5 MINVALUE -10 MAXVALUE 20 CYCLE START WITH 0;

-- VERIFICANDO SEQUENCES NO DD (CATÁLOGO)
SELECT *
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='SEQ_TA';

-- UTILIZANDO SEQUENCE
SELECT SEQ_TA.NEXTVAL  -- DISPONIBILIZA O PRÓXIMO VALOR DA SEQUENCE
FROM DUAL;

SELECT SEQ_TA.CURRVAL  -- MOSTRA O ÚLTIMO VALOR DA SEQUENCE
FROM DUAL;

-- INCLUINDO DADOS COM A SEQUENCE
DESC TA;

INSERT INTO TA
SELECT SEQ_TA.NEXTVAL,
       FIRST_NAME,
       NULL
FROM EMP;

SELECT *
FROM TA;

-- INCLUINDO COMENTÁRIOS EM TABELAS E COLUNAS DE TABELAS
COMMENT ON TABLE TA IS 'Exemplo de inclusão de comentário de tabela.';
COMMENT ON TABLE TA IS '';

-- VISUALIZANDO OS COMENTÁRIOS DE TABELAS
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='TA';

-- COMENTANDO COLUNAS
COMMENT ON COLUMN TA.C1 IS 'Exemplo de inclusão de comentário PARA COLUNA C1 da tabela TA.';
COMMENT ON COLUMN TA.C2 IS 'Exemplo de inclusão de comentário PARA COLUNA C2 da tabela TA.';
COMMENT ON COLUMN TA.C3 IS 'Exemplo de inclusão de comentário PARA COLUNA C3 da tabela TA.';

-- VISUALIZANDO OS COMENTÁRIOS DE COLUNAS DE TABELAS
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='TA';

-- INSERINDO DADOS NO BD DE PEDIDO
SELECT *
FROM DEMO.CLIENTE;
-- COMANDO DE CONTROLE DA TRANSAÇÃO
ROLLBACK; -- DESCARTA TODAS AS ALTERAÇÕES DA TRANSAÇÃO. ENCERRA A TRANSAÇÃO E ABRE UMA NOVA.
COMMIT; -- CONFIRMA TODAS AS ALTERAÇÕES DA TRANSAÇÃO NA PERSISTÊNCIA. ENCERRA A TRANSAÇÃO E ABRE UMA NOVA.
SAVEPOINT; -- PERMITE DESFAZER ALTERAÇÕES ATÉ OS PONTOS DE CONTROLE CRIADOS.
ROLLBACK TO P1;

DESC TA;
-- INSERINDO LINHA-A-LINHA NA TABELA
INSERT INTO TA (C1,C2,C3) VALUES (1,'Teste de inclusão de linha 1.','A');
SAVEPOINT P1;
INSERT INTO TA (C1,C2,C3) VALUES (2,'Teste de inclusão de linha 2.',NULL); -- NULL = ''
SAVEPOINT P2;
INSERT INTO TA (C2,C1) VALUES ('Teste de inclusão de linha 3.',3); 
SAVEPOINT P3;
INSERT INTO TA VALUES (4,'Teste de inclusão de linha 4.','C'); 

-- INSERINDO MULTIPLAS LINHAS NA TABELA A PARTIR FONTE DE DADOS
INSERT INTO TA (C1,C2,C3)
SELECT ID,
       CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME), -- FIRST_NAME||' '||LAST_NAME
       SUBSTR(USERID,1,1)
FROM EMP;

INSERT INTO CLIENTE
SELECT *
FROM DEMO.CLIENTE;

SELECT *
FROM CLIENTE;

SELECT *
FROM TA;

-- TRABALHANDO COM JUNÇÕES TABELAS
SELECT A.NUMERO AS PEDIDO,
       A.DATA DATA_PEDIDO
FROM (SELECT * FROM PEDIDO P) A;  -- UTILIZANDO SUBQUERY NA QUERY
                                  -- APELIDO PARA PEDIDO (P) NA SUBQUERY E APELIDO PARA A 
                                  -- SUBQUERY (A)

SELECT A.NUMERO AS PEDIDO,
       A.DATA DATA_PEDIDO,
       A.CODIGO_CLI AS CODIGO_CLIENTE,
       B.CODIGO,
       B.NOME CLIENTE,
       D.NOME AS VENDEDOR,
       FONE_CLIENTE.NUMERO FONE
FROM (PEDIDO A INNER JOIN
     CLIENTE B ON A.CODIGO_CLI = B.CODIGO) JOIN
     VENDEDOR D ON A.MATRICULA_VEN = D.MATRICULA LEFT JOIN
     FONE_CLIENTE ON FONE_CLIENTE.CODIGO_CLI = B.CODIGO
WHERE FONE_CLIENTE.CODIGO_CLI IS NULL;

-- UTILIZANDO AS FUNÇÕES DE GRUPO
-- FUNÇÕES DE GRUPO: AVG, SUM, COUNT, MIN, MAX
SELECT --DATA,
       MIN(NUMERO) AS MENOR_NR,
       MAX(NUMERO) AS MAIOR_NR,
       AVG(NUMERO) AS MEDIA_NR,
       COUNT(NUMERO) AS QDE_NR,
       SUM(NUMERO) AS SOMA_NR
FROM PEDIDO
WHERE MOD(TO_CHAR(DATA,'DD'),2) = 1 -- MOSTRANDO O RESULTADO SOMENTE PARA NUMERO PAR
GROUP BY DATA

--HAVING COUNT(NUMERO) > 1
ORDER BY MENOR_NR;

-- EXCLUINDO VALORES DE CAMPOS EM TABELAS
DELETE FROM TAB/VIEW
WHERE <CODIÇÃO>;

SELECT *
FROM TA;

DELETE FROM TA
WHERE C1=10;

SELECT *
FROM TA
WHERE C1=10;

ROLLBACK;

SELECT *
FROM TA
WHERE SUBSTR(C2,1,1)='A'
   OR (SUBSTR(C2,1,1)='B'
  AND SUBSTR(C2,-1)='n') ;
  
DELETE FROM TA
WHERE SUBSTR(C2,1,1)='A'
   OR (SUBSTR(C2,1,1)='B'
  AND SUBSTR(C2,-1)='n') ;
  
-- TRABALHANDO COM VIEWS
DROP VIEW VW_PEDIDO_CLIENTE;

CREATE OR REPLACE VIEW VW_PEDIDO_CLIENTE
AS
SELECT P.NUMERO AS PEDIDO,
       P.DATA,
       P.TOTAL_FATURA TOTAL_FATURA,
       C.NOME AS CLIENTE
FROM PEDIDO P INNER JOIN
     CLIENTE C ON P.CODIGO_CLI=C.CODIGO
WHERE TOTAL_FATURA > 5000
ORDER BY TOTAL_FATURA DESC;

SELECT *
FROM VW_PEDIDO_CLIENTE
WHERE TOTAL_FATURA > 10000;

DESC VW_PEDIDO_CLIENTE;

SELECT VPC.*,
       IP.*
FROM VW_PEDIDO_CLIENTE VPC INNER JOIN
     ITEM_PRODUTO IP ON VPC.PEDIDO=IP.NUMERO_PED
ORDER BY PEDIDO;

-- VIEW_CLIENTE
CREATE OR REPLACE VIEW VIEW_CLIENTE
AS
SELECT 'PF' AS TIPO,
CODIGO,
NOME,
CNPF,
NULL AS CNPJ
FROM CLIENTE JOIN
PF ON CLIENTE.CODIGO = PF.CODIGO_CLI
UNION
SELECT 'PJ' AS TIPO,
CODIGO,
NOME,
NULL AS CNPF,
CNPJ
FROM CLIENTE JOIN
PJ ON CLIENTE.CODIGO = PJ.CODIGO_CLI;

SELECT *
FROM VIEW_CLIENTE;

CREATE OR REPLACE VIEW VIEW_CLIENTE1
AS
SELECT CASE
WHEN CNPF IS NULL THEN 'PJ'
ELSE 'PF'
END AS TIPO,
CODIGO,
NOME,
CNPF,
CNPJ
FROM CLIENTE LEFT JOIN
PF ON CLIENTE.CODIGO = PF.CODIGO_CLI LEFT JOIN
PJ ON CLIENTE.CODIGO = PJ.CODIGO_CLI
WHERE (CNPF IS NULL AND CNPJ IS NOT NULL)
OR (CNPJ IS NULL AND CNPF IS NOT NULL);

-- VISUALIZANDO OS METADADOS DA VIEW CRIADA
SELECT *
FROM USER_VIEWS
WHERE VIEW_NAME='VW_PEDIDO_CLIENTE';

SELECT P.NUMERO AS PEDIDO,
       P.DATA,
       P.TOTAL_FATURA TOTAL_FATURA,
       C.NOME AS CLIENTE
FROM PEDIDO P INNER JOIN
     CLIENTE C ON P.CODIGO_CLI=C.CODIGO
WHERE TOTAL_FATURA > 5000
ORDER BY TOTAL_FATURA DESC;

-- PLANO DE EXECUÇÃO
EXPLAIN PLAN FOR
SELECT  NUMERO,
        DATA,
        TOTAL_FATURA as TOTAL,
        NOME AS CLIENTE
FROM    PEDIDO JOIN
        VIEW_CLIENTE ON CODIGO_CLI=CODIGO;
        
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

--
SELECT * FROM ALUNOS;

DESC ALUNOS;

CREATE TABLE ALUNOS 
AS
SELECT *
FROM ALUNO.ALUNOS;

DESC LOG_ALUNO;

CREATE TABLE LOG_ALUNO (
ACAO            VARCHAR(6),
DATA_ALTERACAO  DATE
);

CREATE OR REPLACE TRIGGER trg_auditoria_aluno
AFTER INSERT OR UPDATE OR DELETE ON alunos
FOR EACH ROW
DECLARE
v_acao VARCHAR(6);
BEGIN
    IF INSERTING THEN
        v_acao := 'INSERT';
    ELSIF UPDATING THEN
        v_acao := 'UPDATE';
    ELSIF DELETING THEN
        v_acao := 'DELETE';
    END IF;
    INSERT INTO log_aluno (acao, data_alteracao)
    VALUES (
    V_ACAO,
    SYSDATE
            );
END;

SELECT *
FROM ALUNOS;

SELECT *
FROM LOG_ALUNO;

DESC ALUNOS;

INSERT INTO ALUNOS VALUES (102,'JOÃO DA SILVA','11/02/1970','EMAILGGG@EDU.BR');